//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindRead.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindRead.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;AllKeyDesc&gt;
        ///  &lt;item&gt;
        ///    &lt;Key&gt;KeyCode&lt;/Key&gt;
        ///    &lt;Value&gt;从键值提取键代码的位屏蔽&lt;/Value&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;Key&gt;Modifiers&lt;/Key&gt;
        ///    &lt;Value&gt;从键值提取修饰符的位屏蔽&lt;/Value&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;Key&gt;None&lt;/Key&gt;
        ///    &lt;Value&gt;没有按任何键&lt;/Value&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;Key&gt;LButton&lt;/Key&gt;
        ///    &lt;Value&gt;鼠标左按钮&lt;/Value&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;Key&gt;RButton&lt;/Key&gt;
        ///    &lt;Value&gt;鼠标右按钮&lt;/Value&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;Key&gt;Cancel&lt;/Key&gt;
        ///    &lt;Value&gt;Cancel键&lt;/Value&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;K [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AllKeyDesc {
            get {
                return ResourceManager.GetString("AllKeyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap book {
            get {
                object obj = ResourceManager.GetObject("book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon bookShow {
            get {
                object obj = ResourceManager.GetObject("bookShow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- 默认热键设置 --&gt;
        ///&lt;HotKeys&gt;
        ///  &lt;item&gt;
        ///    &lt;keyCode&gt;Left&lt;/keyCode&gt;
        ///    &lt;effect&gt;上一页&lt;/effect&gt;
        ///    &lt;explain&gt;向左键&lt;/explain&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;keyCode&gt;Right&lt;/keyCode&gt;
        ///    &lt;effect&gt;下一页&lt;/effect&gt;
        ///    &lt;explain&gt;向右键&lt;/explain&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;keyCode&gt;Up&lt;/keyCode&gt;
        ///    &lt;effect&gt;上一页&lt;/effect&gt;
        ///    &lt;explain&gt;向上键&lt;/explain&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;keyCode&gt;Down&lt;/keyCode&gt;
        ///    &lt;effect&gt;下一页&lt;/effect&gt;
        ///    &lt;explain&gt;向下键&lt;/explain&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;keyCode&gt;Oemti [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DefaultHotKey {
            get {
                return ResourceManager.GetString("DefaultHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--预置配色--&gt;
        ///&lt;DefaultPresetColor&gt;
        ///	&lt;item&gt;
        ///		&lt;name&gt;纯白&lt;/name&gt;
        ///		&lt;index&gt;0&lt;/index&gt;
        ///		&lt;backColor&gt;255,255,255&lt;/backColor&gt;
        ///		&lt;foreColor&gt;0,0,0&lt;/foreColor&gt;
        ///		&lt;promptColor&gt;254,153,0&lt;/promptColor&gt;
        ///		&lt;selectionColor&gt;93,226,231&lt;/selectionColor&gt;
        ///		&lt;otherColor&gt;180,181,182&lt;/otherColor&gt;
        ///	&lt;/item&gt;
        ///	&lt;item&gt;
        ///		&lt;name&gt;藏青&lt;/name&gt;
        ///		&lt;index&gt;1&lt;/index&gt;
        ///		&lt;backColor&gt;51,63,80&lt;/backColor&gt;
        ///		&lt;foreColor&gt;180,181,182&lt;/foreColor&gt;
        ///		&lt;promptColor&gt;255,99,71&lt;/promptColor&gt;
        ///		&lt;selectionColor&gt;12 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DefaultPresetColor {
            get {
                return ResourceManager.GetString("DefaultPresetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_book_shelf_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_book_shelf_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_bookmark_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_bookmark_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_news_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_news_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_opened_folder_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_opened_folder_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_restart_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_restart_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_search_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_search_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_services_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_services_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_settings_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_settings_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icons8_storytelling_50 {
            get {
                object obj = ResourceManager.GetObject("icons8_storytelling_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
